
-- Create table for assets
CREATE TABLE assets (
    asset_name VARCHAR(255)PRIMARY KEY, --computer name
    ip_addr VARCHAR(255),
    type VARCHAR(255),
    registration_date TIMESTAMP
);

-- Create table for users
CREATE TABLE users (
    username VARCHAR(255) PRIMARY KEY,
    registration_date DATE
);

-- Create table for events
CREATE TABLE events (
    event_id INT PRIMARY KEY,
    event_type VARCHAR(255),
    description VARCHAR2(4000),
    username_regex VARCHAR(255),
    evidence_regex VARCHAR(255)
);

-- Create table for log files
CREATE TABLE log_files (
    file_id VARCHAR(255) PRIMARY KEY,
    file_name VARCHAR(255),
    file_path VARCHAR2(4000)
);

-- Create table for log activities
CREATE TABLE log_activity (
    activity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id VARCHAR(255),
    event_id INT,
    event_time DATE,
    asset_name VARCHAR(255),
    username VARCHAR(255),
    evidence VARCHAR2(4000),
    FOREIGN KEY (file_id) REFERENCES log_files(file_id),
    FOREIGN KEY (event_id) REFERENCES events(event_id),
    FOREIGN KEY (username) REFERENCES users(username),
    FOREIGN KEY (asset_name) REFERENCES assets(asset_name)
);



-- Create table for concordance
CREATE TABLE concordance (
    word_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(255),
    file_id VARCHAR(255),
    row_num INT,
    word_num INT,
    groups VARCHAR(255),
    FOREIGN KEY (file_id) REFERENCES log_files(file_id),
    UNIQUE (word, file_id, row_num, word_num)
);

-- Create a view that combines data from assets, users, events, log_files, log_activity, and concordance tables
CREATE VIEW combined_data_view AS
SELECT
    a.asset_name,
    a.ip_addr,
    a.type AS asset_type,
    a.registration_date AS asset_registration_date,
    u.username,
    u.registration_date AS user_registration_date,
    e.event_id,
    e.event_type,
    e.description AS event_description,
    e.username_regex,
    e.evidence_regex,
    lf.file_id AS log_file_id,
    lf.file_name,
    lf.file_path AS log_file_path,
    la.activity_id,
    la.event_time AS activity_event_time,
    la.evidence AS activity_evidence,
    c.word_id AS concordance_word_id,
    c.word AS concordance_word,
    c.row_num AS concordance_row_num,
    c.word_num AS concordance_word_num,
    c.groups AS concordance_groups
FROM
    log_files lf
LEFT JOIN
    log_activity la ON lf.file_id = la.file_id
LEFT JOIN
    users u ON la.asset_name = u.username
LEFT JOIN
    events e ON la.event_id = e.event_id
LEFT JOIN
    assets a ON la.asset_name = a.asset_name    
LEFT JOIN
    concordance c ON lf.file_id = c.file_id;

