
-- Create table for assets
CREATE TABLE assets (
    asset_name VARCHAR(255)PRIMARY KEY, --computer name
    ip_addr VARCHAR(255),
    type VARCHAR(255),
    registration_date TIMESTAMP
);

-- Create table for users
CREATE TABLE users (
    username VARCHAR(255) PRIMARY KEY,
    registration_date DATE
);

-- Create table for events
CREATE TABLE events (
    event_id INT PRIMARY KEY,
    event_type VARCHAR(255),
    description VARCHAR2(4000),
    username_regex VARCHAR(255),
    evidence_regex VARCHAR(255)
);

-- Create table for log files
CREATE TABLE log_files (
    file_id VARCHAR(255) PRIMARY KEY,
    file_name VARCHAR(255),
    file_path VARCHAR2(4000)
);

-- Create table for log activities
CREATE TABLE log_activity (
    activity_id INT PRIMARY KEY,
    file_id VARCHAR(255),
    event_id INT,
    event_time DATE,
    asset_name VARCHAR(255),
    username VARCHAR(255),
    evidence VARCHAR2(4000),
    FOREIGN KEY (file_id) REFERENCES log_files(file_id),
    FOREIGN KEY (event_id) REFERENCES events(event_id),
    FOREIGN KEY (username) REFERENCES users(username),
    FOREIGN KEY (asset_name) REFERENCES assets(asset_name)
);



-- Create table for concordance
CREATE TABLE concordance (
    word_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(255),
    file_id VARCHAR(255),
    row_num INT,
    word_num INT,
    FOREIGN KEY (file_id) REFERENCES log_files(file_id)
);

